# Don't change this
version: 1
# bStats metrics
metrics: true

replace:
  villagers:
    # Replace monument map offers from villagers
    monument: false
    # Replace mansion map offers from villagers
    mansion: false
    # Replace trial chamber map offers from villagers
    trial_chamber: true
